CREATE TABLE [dbo].[File]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[FileName] VARCHAR(150) NOT NULL,
	[MimeTypeId] INT NOT NULL,
	[FileData] VARBINARY(MAX),
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[LastModified] DATETIME2 NULL,
	CONSTRAINT [FK_File_MimeType] FOREIGN KEY ([MimeTypeId]) REFERENCES [MimeType]([Id])
)
