CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Username] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(50) NOT NULL,
	[Password] VARCHAR(250) NOT NULL,
	[Salt] VARCHAR(250) NOT NULL,
	[IsLocked] BIT NOT NULL DEFAULT 0,
	[IsDeleted] BIT NOT NULL DEFAULT 0,
	[CreatedOn] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[LastModified] DATETIME2 NULL,
	CONSTRAINT [U_User_Username] UNIQUE([Username]),
	CONSTRAINT [U_User_Email] UNIQUE([Email])
)
