//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDatalayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Tags = new HashSet<Tag>();
            this.PostContents = new HashSet<PostContent>();
        }
    
        public int Id { get; set; }
        public int AuthorId { get; set; }
        public bool IsPublic { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<PostContent> PostContents { get; set; }
    }
}
